name: career_pulse
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  fluttertoast: ^8.2.6
  cloud_firestore: ^5.1.0
  pub_updater: ^0.4.0
  google_sign_in: ^6.2.1
  file_picker: ^4.1.6
  url_launcher: ^6.3.0
  provider: ^6.0.0
  

 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0




flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/playstore.png"
  image_path_ios: "assets/appstore.png"
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200

 