// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9XgmJFYpnc2aPwSA8FT01ORSKL94NB5Q',
    appId: '1:695544969833:web:e4b245e2e6a5cc6b6b40f8',
    messagingSenderId: '695544969833',
    projectId: 'careerpulse1',
    authDomain: 'careerpulse1.firebaseapp.com',
    storageBucket: 'careerpulse1.appspot.com',
    measurementId: 'G-F0JF8KRCWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT9XrnCCSU-pidoOgIpcdr7Xxzuo-3cik',
    appId: '1:695544969833:android:f1b7e706074cd9306b40f8',
    messagingSenderId: '695544969833',
    projectId: 'careerpulse1',
    storageBucket: 'careerpulse1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxj0fSW9pZRhKX30NNSn8oHhsiEEj1h2A',
    appId: '1:695544969833:ios:a33847911d84159c6b40f8',
    messagingSenderId: '695544969833',
    projectId: 'careerpulse1',
    storageBucket: 'careerpulse1.appspot.com',
    iosClientId: '695544969833-vtj3hi5l95ia8ta9c9e4ftqqbv70kc3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxj0fSW9pZRhKX30NNSn8oHhsiEEj1h2A',
    appId: '1:695544969833:ios:a33847911d84159c6b40f8',
    messagingSenderId: '695544969833',
    projectId: 'careerpulse1',
    storageBucket: 'careerpulse1.appspot.com',
    iosClientId: '695544969833-vtj3hi5l95ia8ta9c9e4ftqqbv70kc3s.apps.googleusercontent.com',
    iosBundleId: 'com.example.careerPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9XgmJFYpnc2aPwSA8FT01ORSKL94NB5Q',
    appId: '1:695544969833:web:f2a6985fe4356b756b40f8',
    messagingSenderId: '695544969833',
    projectId: 'careerpulse1',
    authDomain: 'careerpulse1.firebaseapp.com',
    storageBucket: 'careerpulse1.appspot.com',
    measurementId: 'G-Y5VF5WJC8Y',
  );

}